import os

from dotenv import load_dotenv

# 加载 .env 文件，默认在项目根目录
load_dotenv('../../.env')

# 读取配置项
CLICKHOUSE_HOST = os.getenv("CLICKHOUSE_HOST")
CLICKHOUSE_PORT = int(os.getenv("CLICKHOUSE_PORT", 9000))
CLICKHOUSE_DATABASE = os.getenv("CLICKHOUSE_DATABASE")
CLICKHOUSE_USER = os.getenv("CLICKHOUSE_USER")
CLICKHOUSE_PASSWORD = os.getenv("CLICKHOUSE_PASSWORD")

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))
REDIS_DB = int(os.getenv("REDIS_DB", 0))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")

SOUNDCLOUD_CLIENT_ID = os.getenv("SOUNDCLOUD_CLIENT_ID")
SOUNDCLOUD_APP_VERSION = int(os.getenv("SOUNDCLOUD_APP_VERSION", 0))

PROXY_TUNNEL = os.getenv("PROXY_TUNNEL")
PROXY_USER_NAME = os.getenv("PROXY_USER_NAME")
PROXY_PWD = os.getenv("PROXY_PWD")
PROXY_URL = os.getenv("PROXY_URL")


CLASH_GROUP = os.getenv("CLASH_GROUP")
CLASH_URL = os.getenv("CLASH_URL")
CLASH_USER = os.getenv("CLASH_USER")
CLASH_SECRET = os.getenv("CLASH_PASSWORD")

# 可选：打包成字典，方便统一传递
def get_config():
    return {
        "CLICKHOUSE_HOST": CLICKHOUSE_HOST,
        "CLICKHOUSE_PORT": CLICKHOUSE_PORT,
        "CLICKHOUSE_DATABASE": CLICKHOUSE_DATABASE,
        "CLICKHOUSE_USER": CLICKHOUSE_USER,
        "CLICKHOUSE_PASSWORD": CLICKHOUSE_PASSWORD,
        "REDIS_HOST": REDIS_HOST,
        "REDIS_PORT": REDIS_PORT,
        "REDIS_DB": REDIS_DB,
        "REDIS_PASSWORD": REDIS_PASSWORD,
        "SOUNDCLOUD_CLIENT_ID": SOUNDCLOUD_CLIENT_ID,
        "SOUNDCLOUD_APP_VERSION": SOUNDCLOUD_APP_VERSION,
        "PROXY_TUNNEL": PROXY_TUNNEL,
        "PROXY_USER_NAME": PROXY_USER_NAME,
        "PROXY_PWD": PROXY_PWD,
        "PROXY_URL": PROXY_URL,
        "CLASH_GROUP": CLASH_GROUP,
        "CLASH_URL": CLASH_URL,
        "CLASH_USER": CLASH_USER,
        "CLASH_SECRET": CLASH_SECRET,
    }